name: deploy to lambda
on: [push]
jobs:
  deploy:
    environment: Deploy
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Build venv
        run: |
          mkdir package
          pip install --target package -r requirements.txt
          mv modbot.py package/
          cd package
          zip -r ../lambda.zip .
      - name: Deploy lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: giffinator_moderator
          zip_file: lambda.zip
          memory_size: 128
          timeout: 10
          handler: modbot.main
          runtime: python3.13